function newLayer = updateImageLayerInputSize(layer,inputSize)
% Update the image input layer InputSize. This function resets the input
% statistics to allow the size to change. 

% Copyright 2019 The MathWorks, Inc.

% Create the layer.
newLayer = imageInputLayer(inputSize, ...
    'Normalization', layer.Normalization,...
    'NormalizationDimension', layer.NormalizationDimension,...
    'Mean', [],...
    'StandardDeviation', [], ...
    'Min', [], ...
    'Max', [], ...
    'Name', layer.Name);