function hPropDb = getPropertySet
%GETPROPERTYDB Get the propertyDb.

%   Copyright 2022 The MathWorks, Inc.
% 
hPropDb = matlabshared.scopes.visual.Visual.getPropertySet(...
    'AxesProperties','mxArray',[],...
    'ColorMapExpression','string','gray(256)',...
    'UseDataRange','bool',false,...
    'DataRangeMin','double',0,...
    'DataRangeMax','double',255);

% [EOF]
