function renderMenus(this)
%

% Copyright 2022 The MathWorks, Inc.

this.PointCloudInfoMenu = uimenu( ...
    this.Application.Handles.toolsMenu, ...
    'Tag', 'uimgr.uimenu_VideoInfo', ...
    'Label', "Point Cloud Information", ...
    'Callback', @(hco,ev) show(this.PointCloudInfo, true));

end