clear
clc
close all

load("Res101-FINAL.mat", 'net');

%%

ds = fileDatastore("./SmallDSFs/", ReadFcn=@(x)MATReader1C(x, 0)); %training data

%%
options = trainingOptions("adam", ...
    InitialLearnRate=0.001, ...
    LearnRateSchedule="piecewise", ...
    LearnRateDropPeriod=125, ...
    LearnRateDropFactor=0.5, ...
    Plot="none", ...  
    MaxEpochs=200, ...
    MiniBatchSize=1, ...
    ResetInputNormalization=false, ...
    ExecutionEnvironment="cpu", ...
    VerboseFrequency=1, ...
    L2Regularization=1e-5) 

%%
[net,info] = trainMRCNN(ds,net,options, NumStrongestRegions=1000, NumRegionsToSample=100, PositiveOverlapRange=[0.5 1], NegativeOverlapRange=[0 0.5], ForcedPositiveProposals=false, FreezeSubNetwork="backbone")


%%
max(net.RegionProposalNet.Layers(3,1).Weights, [], 'all')

%%