clear
clc
close all

%%
addpath("~/Scratch/MRCNNsrc") %for custom cnn and training loops


trainClassNames = ["CellA"];
imageSizeTrain = [520 704 1];

ABs = [20 20; 20 40; 40 20]*2;
ABs = [ABs*2; ABs*4; ABs*8; 320 320];
NetDataDir = "~/Scratch/NetData/NetDataRes101"
 
net = MRCNN(trainClassNames,ABs, NetDataDir,InputSize=imageSizeTrain, ScaleFactor=[1 1]/16);


ds = fileDatastore("~/Scratch/AllDSFs/DSFs", ReadFcn=@(x)MATReader1C(x)); %training data
valds = fileDatastore("~/Scratch/AllDSFs/ValDSFs", ReadFcn=@(x)MATReader1C(x)); %training data

preview(ds)


%%
if canUseGPU
    executionEnvironment = "gpu";
    gpuDevice(1)
else
    executionEnvironment = "cpu";
end
clear ans

miniBatchsize=4;

%% phase 1, initializing all layers
options = trainingOptions("adam", ...
    InitialLearnRate=1e-5, ...
    LearnRateSchedule="piecewise", ...
    LearnRateDropPeriod=100, ...
    LearnRateDropFactor=1, ...
    Plot="none", ...  
    MaxEpochs=3, ...
    MiniBatchSize=miniBatchsize, ...
    BatchNormalizationStatistics="moving", ...
    ResetInputNormalization=false, ...
    ExecutionEnvironment=executionEnvironment, ...
    CheckpointPath="~/Scratch/Checkpoints", ...
    CheckpointFrequency=10, ...
    CheckpointFrequencyUnit="epoch", ...
    VerboseFrequency=1, ...
    Shuffle="every-epoch", ...
    GradientThreshold=1 )

[net,info1] = trainMaskRCNN(ds,net,options)
save("Res50-Warmup.mat","net", "info");


%% phase 2, focus on region proposal network
options = trainingOptions("adam", ...
    InitialLearnRate=3e-5, ...
    LearnRateSchedule="piecewise", ...
    LearnRateDropPeriod=100, ...
    LearnRateDropFactor=1, ...
    Plot="none", ...  
    MaxEpochs=7, ...
    MiniBatchSize=miniBatchsize, ...
    BatchNormalizationStatistics="moving", ...
    ResetInputNormalization=false, ...
    ExecutionEnvironment=executionEnvironment, ...
    CheckpointPath="~/Scratch/Checkpoints", ...
    CheckpointFrequency=10, ...
    CheckpointFrequencyUnit="epoch", ...
    VerboseFrequency=1, ...
    Shuffle="every-epoch", ...
    GradientThreshold=1 )

[net,info2] = trainMaskRCNN(ds,net,options, "FreezeSubNetwork","backbone")
save("Res50-RPNFOCUS.mat","net", "info");


%% phase 3, train everything
options = trainingOptions("adam", ...
    InitialLearnRate=1e-3, ...
    LearnRateSchedule="piecewise", ...
    LearnRateDropPeriod=10, ...
    LearnRateDropFactor=0.1, ...
    Plot="none", ...  
    MaxEpochs=30, ...
    MiniBatchSize=miniBatchsize, ...
    BatchNormalizationStatistics="moving", ...
    ResetInputNormalization=false, ...
    ExecutionEnvironment=executionEnvironment, ...
    CheckpointPath="~/Scratch/Checkpoints", ...
    CheckpointFrequency=10, ...
    CheckpointFrequencyUnit="epoch", ...
    VerboseFrequency=1, ...
    Shuffle="every-epoch", ...
    ValidationData=valds, ...
    ValidationFrequency=3188*10, ...
    GradientThreshold=1 )

[net,info2] = trainMaskRCNN(ds,net,options, "FreezeSubNetwork","backbone")
save("Res50-FINAL.mat","net", "info");