function renderToolbars(this)
%

% Copyright 2022 The MathWorks, Inc.

 hToolbar = this.Application.Handles.playbackToolbar;
 sep = 'on';
    cb = @this.toggleSettingsDialog;
    this.AxesLimitsButton = uitoggletool(hToolbar, ...
        'Tag', 'uimgr.uitoggletool_Settings', ...
        'CData', this.Application.getIcon('parameters'), ...
        'TooltipString', 'Settings', ...
        'Interruptible', 'off', ...
        'Separator', sep, ...
        'ClickedCallback', cb);
end