classdef disparitySGBMLegacyBuildable < coder.ExternalDependency %#codegen
    % disparitySGBMBuildable - encapsulate semi-global block matching
    % algorithm
    
    % Copyright 2012-2023 The MathWorks, Inc.
    
    
    methods (Static)
        
        function name = getDescriptiveName(~)
            name = 'disparitySGBMLegacyBuildable';
        end
        
        function b = isSupportedContext(~)
            b = true; % supports non-host target
        end
        
        function updateBuildInfo(buildInfo, context)
            buildInfo.addIncludePaths({fullfile(matlabroot,'toolbox', ...
                'vision','builtins','src','ocv','include'), ...
                fullfile(matlabroot,'toolbox', ...
                'images','opencv','opencvcg', 'include')} );
            
            srcPaths = fullfile(matlabroot,'toolbox', ...
                'vision','builtins','src','ocv');
            buildInfo.addSourceFiles({'disparitySGBMCore.cpp'},srcPaths);
            buildInfo.addSourcePaths(srcPaths, 'CVT_GROUP');
            
            buildInfo.addIncludeFiles({'vision_defines.h', ...
                'disparityBM.hpp', ...
                'disparitySGBMCore_api.hpp'});
            
            vision.internal.buildable.portableOpenCVBuildInfo(buildInfo, ...
                context, 'disparitySGBM');
        end
        
        %------------------------------------------------------------------
        % write all supported data-type specific function calls
        function outDisparity = disparitySGBM_compute(image1_u8, image2_u8, opt)
            
            coder.inline('always');
            coder.cinclude('disparitySGBMCore_api.hpp');
            
            nRows = int32(size(image1_u8, 1)); % original(before transpose)
            nCols = int32(size(image1_u8, 2)); % original(before transpose)
            outSize = [nRows nCols];
            outDisparity = coder.nullcopy(zeros(outSize,'single'));
            
            paramStruct = struct( ...
                'preFilterCap', int32(opt.preFilterCap), ...
                'SADWindowSize', int32(opt.SADWindowSize), ...
                'minDisparity', int32(opt.minDisparity), ...
                'numberOfDisparities', int32(opt.numberOfDisparities), ...
                'uniquenessRatio', int32(opt.uniquenessRatio), ...
                'disp12MaxDiff', int32(opt.disp12MaxDiff), ...
                'speckleWindowSize', int32(opt.speckleWindowSize), ...
                'speckleRange', int32(opt.speckleRange), ...
                'P1',int32(opt.P1),...
                'P2',int32(opt.P2),...
                'fullDP',int32(opt.fullDP)...
                );
            
            coder.cstructname(paramStruct,'cvstDSGBMStruct_T', 'extern', 'HeaderFile', 'disparitySGBMCore_api.hpp');
            
            if coder.isColumnMajor
                coder.ceval('-col', 'disparitySGBM_compute',...
                    coder.ref(image1_u8), ...
                    coder.ref(image2_u8), ...
                    nRows, nCols, ...
                    coder.ref(outDisparity), ...
                    coder.ref(paramStruct));
            else
                coder.ceval('-row', 'disparitySGBM_computeRM',...
                    coder.ref(image1_u8), ...
                    coder.ref(image2_u8), ...
                    nRows, nCols, ...
                    coder.ref(outDisparity), ...
                    coder.ref(paramStruct));
            end
            
        end
    end
end
