/* Copyright 2018-2019 The MathWorks, Inc. */

#ifndef _SEARCHORGANIZEDPOINTCLOUD_UTIL_
#define _SEARCHORGANIZEDPOINTCLOUD_UTIL_

#ifndef __portable__
#include "version.h"
#endif

#if defined(BUILDING_LIBMWSEARCHORGANIZEDPOINTCLOUD)
  #define LIBMWSEARCHORGANIZEDPOINTCLOUD_API DLL_EXPORT_SYM
#else
#ifdef __portable__
  #define LIBMWSEARCHORGANIZEDPOINTCLOUD_API
#else
  #define LIBMWSEARCHORGANIZEDPOINTCLOUD_API DLL_IMPORT_SYM
#endif
#endif

#endif 
