function langs = languagesInSupportPackage()
% Returns a cell array of languages contained within the OCR Support
% Package.

%   Copyright 2014-2022 The MathWorks, Inc.

%#codegen
%#ok<*EMCA>

langs = {...
    'afrikaans',...
    'albanian',...
    'ancientgreek',...
    'arabic',...
    'azerbaijani',...
    'basque',...
    'belarusian',...
    'bengali',...
    'bulgarian',...
    'catalan',...
    'cherokee',...
    'chinesesimplified',...
    'chinesetraditional',...
    'croatian',...
    'czech',...
    'danish',...
    'dutch',...
    'english',...
    'esperanto',...
    'esperantoalternative',...
    'estonian',...
    'finnish',...
    'frankish',...
    'french',...
    'galician',...
    'german',...
    'greek',...
    'hebrew',...
    'hindi',...
    'hungarian',...
    'icelandic',...
    'indonesian',...
    'italian',...
    'italianold',...
    'japanese',...
    'kannada',...
    'korean',...
    'latvian',...
    'lithuanian',...
    'macedonian',...
    'malay',...
    'malayalam',...
    'maltese',...
    'mathequation',...
    'middleenglish',...
    'middlefrench',...
    'norwegian',...
    'polish',...
    'portuguese',...
    'romanian',...
    'russian',...
    'serbianlatin',...
    'slovakian',...
    'slovenian',...
    'spanish',...
    'spanishold',...
    'swahili',...
    'swedish',...
    'tagalog',...
    'tamil',...
    'telugu',...
    'thai',...
    'turkish',...
    'ukrainian'}; 
